import { Category, Product } from "@/types";
import { slugify } from "@/util/slugify";

export const dummyCategories: Category[] = [
  { _id: "1", title_en: "Coffee", title_el: "Καφές", description_en: "", description_el: "", image: "" },
  { _id: "2", title_en: "Snacks", title_el: "Σνακ", description_en: "", description_el: "", image: "" },
  { _id: "3", title_en: "Smoothies", title_el: "Smoothies", description_en: "", description_el: "", image: "" },
  { _id: "4", title_en: "Milkshakes", title_el: "Milkshakes", description_en: "", description_el: "", image: "" },
  { _id: "5", title_en: "Ice Teas", title_el: "Παγωμένα Τσάγια", description_en: "", description_el: "", image: "" },
  { _id: "6", title_en: "Coffee Beans", title_el: "Κόκκοι Καφέ", description_en: "", description_el: "", image: "" },
];

export const dummyProducts: Product[] = [
  {
    _id: "1",
    category: "Coffee",
    image: "/coffee.jpg",
    title_en: "Espresso",
    title_el: "Εσπρέσο",
    description_en: "Rich and bold espresso",
    description_el: "Πλούσιο εσπρέσο",
    productName: "espresso",
    slug: slugify("Espresso"),
    price: 2.99,
    ingredients_en: [
      { _id: "i1", title: "Sugar", options: ["Regular", "Low", "None"] },
      { _id: "i2", title: "Size", options: ["Small", "Medium", "Large"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Ζάχαρη", options: ["Κανονική", "Λίγη", "Χωρίς"] },
      { _id: "i2", title: "Μέγεθος", options: ["Μικρό", "Μεσαίο", "Μεγάλο"] },
    ],
    options_en: [],
    options_el: [],
  },
  {
    _id: "2",
    category: "Coffee",
    image: "/coffee.jpg",
    title_en: "Cappuccino",
    title_el: "Καπουτσίνο",
    description_en: "Creamy cappuccino with frothy milk",
    description_el: "Κρεμώδες καπουτσίνο με αφρόγαλα",
    productName: "cappuccino",
    slug: slugify("Cappuccino"),
    price: 3.49,
    ingredients_en: [
      { _id: "i1", title: "Sugar", options: ["Regular", "Low", "None"] },
      { _id: "i2", title: "Milk Type", options: ["Whole", "Skim", "Almond", "Soy"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Ζάχαρη", options: ["Κανονική", "Λίγη", "Χωρίς"] },
      { _id: "i2", title: "Γάλα", options: ["Πλήρες", "Αποβουτυρωμένο", "Αμυγδάλου", "Σόγιας"] },
    ],
    options_en: [],
    options_el: [],
  },
  {
    _id: "3",
    category: "Snacks",
    image: "/snack.jpg",
    title_en: "Muffin",
    title_el: "Μάφιν",
    description_en: "Chocolate chip muffin",
    description_el: "Μάφιν με κομμάτια σοκολάτας",
    productName: "muffin",
    slug: slugify("Muffin"),
    price: 1.99,
    ingredients_en: [
      { _id: "i1", title: "Toppings", options: ["Extra Choc Chips", "Nuts", "Whipped Cream"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Γαρνιτούρα", options: ["Επιπλέον Σοκολάτα", "Ξηροί Καρποί", "Σαντιγί"] },
    ],
    options_en: [],
    options_el: [],
  },
  {
    _id: "4",
    category: "Snacks",
    image: "/snack.jpg",
    title_en: "Croissant",
    title_el: "Κρουασάν",
    description_en: "Buttery and flaky croissant",
    description_el: "Τραγανό και βουτυράτο κρουασάν",
    productName: "croissant",
    slug: slugify("Croissant"),
    price: 2.49,
    ingredients_en: [
      { _id: "i1", title: "Filling", options: ["Chocolate", "Almond", "Cheese"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Γέμιση", options: ["Σοκολάτα", "Αμύγδαλο", "Τυρί"] },
    ],
    options_en: [],
    options_el: [],
  },
  {
    _id: "5",
    category: "Smoothies",
    image: "/smoothie.jpg",
    title_en: "Berry Blast",
    title_el: "Berry Blast",
    description_en: "Mixed berry smoothie with yogurt",
    description_el: "Smoothie με μικτά μούρα και γιαούρτι",
    productName: "berry-blast",
    slug: slugify("Berry Blast"),
    price: 4.99,
    ingredients_en: [
      { _id: "i1", title: "Protein", options: ["Whey", "Soy", "None"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Πρωτεΐνη", options: ["Ορού", "Σόγιας", "Χωρίς"] },
    ],
    options_en: [],
    options_el: [],
  },
  {
    _id: "6",
    category: "Milkshakes",
    image: "/milkshake.jpg",
    title_en: "Chocolate Milkshake",
    title_el: "Σοκολατένιο Milkshake",
    description_en: "Rich chocolate milkshake with whipped cream",
    description_el: "Πλούσιο σοκολατένιο milkshake με σαντιγί",
    productName: "chocolate-milkshake",
    slug: slugify("Chocolate Milkshake"),
    price: 4.99,
    ingredients_en: [
      { _id: "i1", title: "Size", options: ["Small", "Medium", "Large"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Μέγεθος", options: ["Μικρό", "Μεσαίο", "Μεγάλο"] },
    ],
    options_en: [],
    options_el: [],
  },
  {
    _id: "7",
    category: "Ice Teas",
    image: "/icetea.jpg",
    title_en: "Lemon Iced Tea",
    title_el: "Παγωμένο Τσάι Λεμόνι",
    description_en: "Refreshing lemon iced tea with a hint of mint",
    description_el: "Δροσιστικό παγωμένο τσάι λεμόνι με μέντα",
    productName: "lemon-iced-tea",
    slug: slugify("Lemon Iced Tea"),
    price: 3.49,
    ingredients_en: [
      { _id: "i1", title: "Sweetness", options: ["Regular", "Less Sweet", "No Sweetener"] },
      { _id: "i2", title: "Size", options: ["Small", "Medium", "Large"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Γλυκύτητα", options: ["Κανονική", "Λιγότερο", "Χωρίς"] },
      { _id: "i2", title: "Μέγεθος", options: ["Μικρό", "Μεσαίο", "Μεγάλο"] },
    ],
    options_en: [],
    options_el: [],
  },
  {
    _id: "8",
    category: "Coffee Beans",
    image: "/beans.jpg",
    title_en: "Arabica Coffee Beans",
    title_el: "Κόκκοι Arabica",
    description_en: "Premium Arabica coffee beans",
    description_el: "Κόκκοι καφέ Arabica υψηλής ποιότητας",
    productName: "arabica-beans",
    slug: slugify("Arabica Coffee Beans"),
    price: 14.99,
    ingredients_en: [
      { _id: "i1", title: "Grind", options: ["Whole Bean", "Coarse", "Medium", "Fine"] },
    ],
    ingredients_el: [
      { _id: "i1", title: "Άλεσμα", options: ["Ολόκληρος", "Χοντρό", "Μεσαίο", "Ψιλό"] },
    ],
    options_en: [],
    options_el: [],
  },
];
